import { parseFuel, parseTransmission, prefixRegion, slugify } from '../normalize';
import type { NormalizedListing } from '../types';
import { detailUrl, parseDetailPage } from './autobazar-eu-detail';
import type { ScraperSource } from './source-interface';

const BASE = 'https://www.autobazar.eu';

// autobazar.eu is a Next.js SPA whose listing data is server-rendered into a
// `__NEXT_DATA__` <script> tag in every page. The tRPC search API
// (/api/trpc/search.search) ignores page/offset/limit parameters (anti-scrape),
// so to walk the catalog we have to fan out over (brand, model) buckets — each
// SEF URL `/vysledky/osobne-vozidla/<brand>/<model>/` returns a unique top-20
// slice of that bucket. BRAND_MODEL_BUCKETS is generated from a one-off probe
// of all 35 top brands' aggregations; see scripts/gen-autobazar-eu-buckets.ts.

// Type: parseListingsPage takes the full HTML and pulls listings out of
// __NEXT_DATA__. It does not use cheerio because the listing cards on the
// rendered DOM are produced client-side and the server HTML's <a> anchors
// only cover the homepage carousel.

const NEXT_DATA_RE = /<script id="__NEXT_DATA__" type="application\/json">([\s\S]*?)<\/script>/;

type RawListing = {
  id?: string;
  title?: string | null;
  brandValue?: string | null;
  carModelValue?: string | null;
  price?: number | null;
  finalPrice?: number | null;
  listPrice?: number | null;
  year?: number | null;
  yearValue?: number | string | null;
  yearOfProduction?: number | null;
  mileage?: number | null;
  fuelValue?: string | null;
  gearboxValue?: string | null;
  location?: { name?: string | null } | null;
  bodyworkValue?: string | null;
  vin?: string | null;
  views?: number | null;
  viewCount?: number | null;
  isPremium?: boolean | null;
  isPromoted?: boolean | null;
  premium?: boolean | null;
  user?: { phone?: string | null; phoneNumber?: string | null } | null;
};

type TrpcQuery = { queryKey?: unknown[]; state?: { data?: { data?: unknown } } };
type NextDataEnvelope = {
  props?: { pageProps?: { trpcState?: { queries?: TrpcQuery[] } } };
};

function pickListings(parsed: unknown): RawListing[] {
  // Drill into trpcState.queries[].state.data.data — that's where the
  // `search.search` query result is. We accept any query whose data
  // payload is an array of objects with an `id` field.
  const queries = (parsed as NextDataEnvelope)?.props?.pageProps?.trpcState?.queries;
  if (!Array.isArray(queries)) return [];
  for (const q of queries) {
    const arr = q?.state?.data?.data;
    if (
      Array.isArray(arr) &&
      arr.length > 0 &&
      typeof (arr[0] as { id?: unknown })?.id === 'string'
    ) {
      return arr as RawListing[];
    }
  }
  return [];
}

export function parseListingsPage(html: string): NormalizedListing[] {
  const m = NEXT_DATA_RE.exec(html);
  if (!m) return [];
  let parsed: unknown;
  try {
    parsed = JSON.parse(m[1]!);
  } catch {
    return [];
  }
  const rows = pickListings(parsed);
  const seen = new Set<string>();
  const results: NormalizedListing[] = [];

  for (const r of rows) {
    const sourceId = (r.id ?? '').toString();
    if (!sourceId || seen.has(sourceId)) continue;
    seen.add(sourceId);

    const title = r.title ?? null;
    const brand = r.brandValue ?? null;
    const model = r.carModelValue ?? null;
    // /detail/x/<id>/ permanently redirects to the canonical /detail/<slug>/<id>/
    // URL, so we don't need to reconstruct the slug client-side.
    const url = `${BASE}/detail/x/${sourceId}/`;

    const price = r.finalPrice ?? r.price ?? r.listPrice ?? null;
    const yearRaw = r.year ?? r.yearOfProduction ?? r.yearValue ?? null;
    const year =
      typeof yearRaw === 'number'
        ? yearRaw
        : typeof yearRaw === 'string'
          ? Number.parseInt(yearRaw, 10)
          : null;
    const mileage = r.mileage ?? null;
    const fuel = parseFuel(r.fuelValue ?? null);
    const transmission = parseTransmission(r.gearboxValue ?? null);
    const regionRaw = r.location?.name ?? null;
    const region = prefixRegion(regionRaw, 'SK');

    const viewsRaw = r.views ?? r.viewCount ?? null;
    const viewCount =
      typeof viewsRaw === 'number' && Number.isFinite(viewsRaw) && viewsRaw >= 0
        ? viewsRaw
        : null;
    const isFeatured =
      r.isPremium === true || r.premium === true || r.isPromoted === true
        ? true
        : undefined;
    const phoneRaw = r.user?.phone ?? r.user?.phoneNumber ?? null;
    const sellerPhone =
      typeof phoneRaw === 'string' && phoneRaw.trim().length > 0
        ? phoneRaw.trim().slice(0, 32)
        : null;

    results.push({
      source: 'autobazar.eu',
      sourceId,
      url,
      makeSlug: brand ? slugify(brand) : null,
      modelSlug: model ? slugify(model) : null,
      priceEur: typeof price === 'number' && Number.isFinite(price) ? price : null,
      year: typeof year === 'number' && Number.isFinite(year) ? year : null,
      mileageKm: typeof mileage === 'number' && Number.isFinite(mileage) ? mileage : null,
      fuel,
      transmission,
      region,
      rawTitle: title,
      rawPayload: { capturedAt: new Date().toISOString() },
      viewCount,
      isFeatured,
      sellerPhone,
    });
  }

  return results;
}

// All 104 brand SEFs from autobazar.eu's getAggregations: 104 brand-only
// buckets + up to 15 top models per brand = 847 unique (brand, model | null)
// buckets. Generated 2026-05-12. Regenerate via scripts/gen-autobazar-eu-buckets.ts
// when the catalog drifts. Brand-only buckets sit first so the scraper hits
// broad pools before narrow ones.
export const BRAND_MODEL_BUCKETS: ReadonlyArray<{ brand: string; model: string | null }> = [
  { brand: 'skoda', model: null },
  { brand: 'volkswagen', model: null },
  { brand: 'mercedes-benz', model: null },
  { brand: 'bmw', model: null },
  { brand: 'audi', model: null },
  { brand: 'ford', model: null },
  { brand: 'hyundai', model: null },
  { brand: 'kia', model: null },
  { brand: 'peugeot', model: null },
  { brand: 'volvo', model: null },
  { brand: 'toyota', model: null },
  { brand: 'opel', model: null },
  { brand: 'renault', model: null },
  { brand: 'citroen', model: null },
  { brand: 'land-rover', model: null },
  { brand: 'seat', model: null },
  { brand: 'dacia', model: null },
  { brand: 'mazda', model: null },
  { brand: 'nissan', model: null },
  { brand: 'fiat', model: null },
  { brand: 'suzuki', model: null },
  { brand: 'jeep', model: null },
  { brand: 'mg', model: null },
  { brand: 'porsche', model: null },
  { brand: 'mitsubishi', model: null },
  { brand: 'subaru', model: null },
  { brand: 'cupra', model: null },
  { brand: 'tesla', model: null },
  { brand: 'honda', model: null },
  { brand: 'mini', model: null },
  { brand: 'jaguar', model: null },
  { brand: 'lexus', model: null },
  { brand: 'ssangyong', model: null },
  { brand: 'alfa-romeo', model: null },
  { brand: 'chevrolet', model: null },
  { brand: 'dodge', model: null },
  { brand: 'dongfeng', model: null },
  { brand: 'byd', model: null },
  { brand: 'leapmotor', model: null },
  { brand: 'iveco', model: null },
  { brand: 'jaecoo', model: null },
  { brand: 'lynk-co', model: null },
  { brand: 'ds', model: null },
  { brand: 'omoda', model: null },
  { brand: 'kgm', model: null },
  { brand: 'cadillac', model: null },
  { brand: 'baic', model: null },
  { brand: 'maserati', model: null },
  { brand: 'hongqi', model: null },
  { brand: 'smart', model: null },
  { brand: 'chery', model: null },
  { brand: 'ferrari', model: null },
  { brand: 'lada', model: null },
  { brand: 'lamborghini', model: null },
  { brand: 'lancia', model: null },
  { brand: 'xpeng', model: null },
  { brand: 'chrysler', model: null },
  { brand: 'gmc', model: null },
  { brand: 'abarth', model: null },
  { brand: 'aston-martin', model: null },
  { brand: 'bentley', model: null },
  { brand: 'infiniti', model: null },
  { brand: 'zeekr', model: null },
  { brand: 'forthing', model: null },
  { brand: 'ineos', model: null },
  { brand: 'saab', model: null },
  { brand: 'evo', model: null },
  { brand: 'voyah', model: null },
  { brand: 'hummer', model: null },
  { brand: 'isuzu', model: null },
  { brand: 'dr', model: null },
  { brand: 'rolls-royce', model: null },
  { brand: 'mclaren', model: null },
  { brand: 'man', model: null },
  { brand: 'ich-x', model: null },
  { brand: 'polestar', model: null },
  { brand: 'genesis', model: null },
  { brand: 'sportequipe', model: null },
  { brand: 'daewoo', model: null },
  { brand: 'lincoln', model: null },
  { brand: 'buick', model: null },
  { brand: 'alpina', model: null },
  { brand: 'rover', model: null },
  { brand: 'tatra', model: null },
  { brand: 'dfsk', model: null },
  { brand: 'aito', model: null },
  { brand: 'austin', model: null },
  { brand: 'daihatsu', model: null },
  { brand: 'mahindra', model: null },
  { brand: 'uaz', model: null },
  { brand: 'xev', model: null },
  { brand: 'lotus', model: null },
  { brand: 'maybach', model: null },
  { brand: 'multicar', model: null },
  { brand: 'pontiac', model: null },
  { brand: 'trabant', model: null },
  { brand: 'great-wall', model: null },
  { brand: 'velor', model: null },
  { brand: 'swm', model: null },
  { brand: 'corvette', model: null },
  { brand: 'ora', model: null },
  { brand: 'foton', model: null },
  { brand: 'denza', model: null },
  { brand: 'geely', model: null },
  { brand: 'skoda', model: 'octavia-combi' },
  { brand: 'skoda', model: 'octavia' },
  { brand: 'skoda', model: 'superb-combi' },
  { brand: 'skoda', model: 'kodiaq' },
  { brand: 'volkswagen', model: 'passat-variant' },
  { brand: 'kia', model: 'sportage' },
  { brand: 'skoda', model: 'fabia' },
  { brand: 'volkswagen', model: 'tiguan' },
  { brand: 'skoda', model: 'karoq' },
  { brand: 'volkswagen', model: 'golf-variant' },
  { brand: 'skoda', model: 'superb' },
  { brand: 'hyundai', model: 'tucson' },
  { brand: 'skoda', model: 'fabia-combi' },
  { brand: 'volkswagen', model: 'golf' },
  { brand: 'skoda', model: 'scala' },
  { brand: 'bmw', model: 'x5' },
  { brand: 'hyundai', model: 'i30' },
  { brand: 'volvo', model: 'xc60' },
  { brand: 'volkswagen', model: 'touran' },
  { brand: 'volkswagen', model: 'touareg' },
  { brand: 'skoda', model: 'kamiq' },
  { brand: 'ford', model: 'kuga' },
  { brand: 'mercedes-benz', model: 'glc-suv' },
  { brand: 'volvo', model: 'xc90' },
  { brand: 'peugeot', model: '3008' },
  { brand: 'audi', model: 'a6-avant' },
  { brand: 'bmw', model: 'x3' },
  { brand: 'kia', model: 'cee-d-sw' },
  { brand: 'bmw', model: 'rad-5' },
  { brand: 'mercedes-benz', model: 'gle-suv' },
  { brand: 'dacia', model: 'duster' },
  { brand: 'nissan', model: 'qashqai' },
  { brand: 'peugeot', model: '2008' },
  { brand: 'audi', model: 'a4-avant' },
  { brand: 'mercedes-benz', model: 'a-trieda' },
  { brand: 'bmw', model: 'rad-5-touring' },
  { brand: 'citroen', model: 'c3' },
  { brand: 'bmw', model: 'x1' },
  { brand: 'audi', model: 'q7' },
  { brand: 'peugeot', model: '308-break-sw' },
  { brand: 'hyundai', model: 'i30-cw' },
  { brand: 'bmw', model: 'rad-3-touring' },
  { brand: 'peugeot', model: '208' },
  { brand: 'audi', model: 'q5' },
  { brand: 'volvo', model: 'xc40' },
  { brand: 'skoda', model: 'rapid' },
  { brand: 'toyota', model: 'rav4' },
  { brand: 'ford', model: 'focus-kombi' },
  { brand: 'seat', model: 'leon' },
  { brand: 'bmw', model: 'rad-3' },
  { brand: 'land-rover', model: 'range-rover-sport' },
  { brand: 'mercedes-benz', model: 'gla' },
  { brand: 'hyundai', model: 'i20' },
  { brand: 'bmw', model: 'x6' },
  { brand: 'ford', model: 'ranger' },
  { brand: 'peugeot', model: '5008' },
  { brand: 'volkswagen', model: 'sharan' },
  { brand: 'opel', model: 'astra-sport-tourer' },
  { brand: 'volkswagen', model: 'polo' },
  { brand: 'bmw', model: 'rad-7' },
  { brand: 'ford', model: 'mondeo-combi' },
  { brand: 'ford', model: 'focus' },
  { brand: 'land-rover', model: 'defender' },
  { brand: 'bmw', model: 'rad-1' },
  { brand: 'cupra', model: 'formentor' },
  { brand: 'mg', model: 'zs' },
  { brand: 'volkswagen', model: 'passat' },
  { brand: 'toyota', model: 'yaris' },
  { brand: 'skoda', model: 'yeti' },
  { brand: 'volkswagen', model: 'tiguan-allspace' },
  { brand: 'mercedes-benz', model: 'e-trieda-sedan' },
  { brand: 'kia', model: 'cee-d' },
  { brand: 'dacia', model: 'sandero' },
  { brand: 'mercedes-benz', model: 'c-trieda-kombi' },
  { brand: 'opel', model: 'corsa' },
  { brand: 'opel', model: 'astra' },
  { brand: 'citroen', model: 'c4' },
  { brand: 'mercedes-benz', model: 'e-trieda-kombi' },
  { brand: 'mercedes-benz', model: 'c-trieda-sedan' },
  { brand: 'mercedes-benz', model: 'v-trieda' },
  { brand: 'volvo', model: 'v60' },
  { brand: 'land-rover', model: 'discovery' },
  { brand: 'ford', model: 's-max' },
  { brand: 'peugeot', model: '308' },
  { brand: 'audi', model: 'a6' },
  { brand: 'ford', model: 'tourneo-custom' },
  { brand: 'tesla', model: 'model-3' },
  { brand: 'volkswagen', model: 'arteon' },
  { brand: 'mercedes-benz', model: 's-trieda-sedan' },
  { brand: 'citroen', model: 'berlingo' },
  { brand: 'mercedes-benz', model: 'glb' },
  { brand: 'kia', model: 'sorento' },
  { brand: 'suzuki', model: 'vitara' },
  { brand: 'renault', model: 'clio' },
  { brand: 'mercedes-benz', model: 'gls' },
  { brand: 'ford', model: 'transit' },
  { brand: 'audi', model: 'q3' },
  { brand: 'honda', model: 'cr-v' },
  { brand: 'mercedes-benz', model: 'cla-kupe' },
  { brand: 'opel', model: 'insignia' },
  { brand: 'mazda', model: 'cx-5' },
  { brand: 'ford', model: 'fiesta' },
  { brand: 'opel', model: 'mokka' },
  { brand: 'hyundai', model: 'santa-fe' },
  { brand: 'toyota', model: 'corolla' },
  { brand: 'mazda', model: '3' },
  { brand: 'seat', model: 'ateca' },
  { brand: 'mg', model: 'hs' },
  { brand: 'hyundai', model: 'kona' },
  { brand: 'renault', model: 'captur' },
  { brand: 'porsche', model: 'cayenne' },
  { brand: 'subaru', model: 'outback' },
  { brand: 'audi', model: 'e-tron' },
  { brand: 'mercedes-benz', model: 'gle-kupe' },
  { brand: 'land-rover', model: 'range-rover-evoque' },
  { brand: 'ford', model: 'transit-custom' },
  { brand: 'toyota', model: 'c-hr' },
  { brand: 'land-rover', model: 'range-rover' },
  { brand: 'seat', model: 'alhambra' },
  { brand: 'kia', model: 'xceed' },
  { brand: 'mercedes-benz', model: 'b-trieda' },
  { brand: 'kia', model: 'stonic' },
  { brand: 'bmw', model: 'x7' },
  { brand: 'volkswagen', model: 't-roc' },
  { brand: 'land-rover', model: 'range-rover-velar' },
  { brand: 'jeep', model: 'compass' },
  { brand: 'audi', model: 'a6-allroad' },
  { brand: 'peugeot', model: 'rifter' },
  { brand: 'skoda', model: 'rapid-spaceback' },
  { brand: 'volkswagen', model: 't-cross' },
  { brand: 'renault', model: 'megane' },
  { brand: 'jeep', model: 'grand-cherokee' },
  { brand: 'mitsubishi', model: 'asx' },
  { brand: 'ssangyong', model: 'korando' },
  { brand: 'volvo', model: 'v90' },
  { brand: 'seat', model: 'tarraco' },
  { brand: 'dacia', model: 'jogger' },
  { brand: 'mitsubishi', model: 'outlander' },
  { brand: 'skoda', model: 'roomster' },
  { brand: 'nissan', model: 'x-trail' },
  { brand: 'citroen', model: 'c5-aircross' },
  { brand: 'tesla', model: 'model-y' },
  { brand: 'land-rover', model: 'discovery-sport' },
  { brand: 'dacia', model: 'bigster' },
  { brand: 'volkswagen', model: 'id4' },
  { brand: 'citroen', model: 'c3-aircross' },
  { brand: 'audi', model: 'a3-sportback' },
  { brand: 'kia', model: 'ceed' },
  { brand: 'audi', model: 'q8' },
  { brand: 'fiat', model: '500' },
  { brand: 'ford', model: 'c-max' },
  { brand: 'bmw', model: 'x4' },
  { brand: 'opel', model: 'zafira' },
  { brand: 'volkswagen', model: 'caddy' },
  { brand: 'kia', model: 'rio' },
  { brand: 'audi', model: 'a8' },
  { brand: 'renault', model: 'megane-grandtour' },
  { brand: 'jeep', model: 'wrangler' },
  { brand: 'jaguar', model: 'f-pace' },
  { brand: 'dodge', model: 'ram' },
  { brand: 'ford', model: 'mondeo' },
  { brand: 'kia', model: 'pro-cee-d' },
  { brand: 'fiat', model: 'ducato' },
  { brand: 'renault', model: 'trafic' },
  { brand: 'suzuki', model: 'sx4-s-cross' },
  { brand: 'opel', model: 'crossland' },
  { brand: 'suzuki', model: 'swift' },
  { brand: 'toyota', model: 'corolla-combi' },
  { brand: 'seat', model: 'ibiza' },
  { brand: 'toyota', model: 'proace' },
  { brand: 'opel', model: 'insignia-st' },
  { brand: 'bmw', model: 'rad-4-gran-coupe' },
  { brand: 'citroen', model: 'c4-picasso' },
  { brand: 'mg', model: 'mg3' },
  { brand: 'audi', model: 'a4' },
  { brand: 'audi', model: 'a5-sportback' },
  { brand: 'hyundai', model: 'ix35' },
  { brand: 'ford', model: 'galaxy' },
  { brand: 'ford', model: 'puma' },
  { brand: 'subaru', model: 'forester' },
  { brand: 'skoda', model: 'enyaq' },
  { brand: 'mazda', model: '6-combi-wagon' },
  { brand: 'lexus', model: 'rx' },
  { brand: 'fiat', model: 'panda' },
  { brand: 'mini', model: 'cooper' },
  { brand: 'nissan', model: 'juke' },
  { brand: 'suzuki', model: 'sx4' },
  { brand: 'mini', model: 'countryman' },
  { brand: 'renault', model: 'arkana' },
  { brand: 'mazda', model: 'cx-60' },
  { brand: 'seat', model: 'arona' },
  { brand: 'ford', model: 'mustang' },
  { brand: 'opel', model: 'grandland' },
  { brand: 'audi', model: 'a5' },
  { brand: 'renault', model: 'scenic' },
  { brand: 'alfa-romeo', model: 'stelvio' },
  { brand: 'audi', model: 'a3' },
  { brand: 'toyota', model: 'land-cruiser' },
  { brand: 'kia', model: 'k4' },
  { brand: 'peugeot', model: '508-sw' },
  { brand: 'toyota', model: 'proace-verso' },
  { brand: 'hyundai', model: 'bayon' },
  { brand: 'opel', model: 'frontera' },
  { brand: 'renault', model: 'kangoo' },
  { brand: 'opel', model: 'meriva' },
  { brand: 'mazda', model: 'cx-30' },
  { brand: 'honda', model: 'civic' },
  { brand: 'volvo', model: 'ex30' },
  { brand: 'toyota', model: 'corolla-cross' },
  { brand: 'seat', model: 'leon-st' },
  { brand: 'toyota', model: 'hilux' },
  { brand: 'citroen', model: 'jumper' },
  { brand: 'porsche', model: 'panamera' },
  { brand: 'bmw', model: 'x2' },
  { brand: 'peugeot', model: 'traveller' },
  { brand: 'renault', model: 'grand-scenic' },
  { brand: 'porsche', model: 'macan' },
  { brand: 'peugeot', model: 'boxer' },
  { brand: 'bmw', model: 'rad-3-gt' },
  { brand: 'hyundai', model: 'i30-fastback' },
  { brand: 'lynk-co', model: '01' },
  { brand: 'opel', model: 'grandland-x' },
  { brand: 'cupra', model: 'terramar' },
  { brand: 'hyundai', model: 'i40' },
  { brand: 'toyota', model: 'auris' },
  { brand: 'renault', model: 'austral' },
  { brand: 'jeep', model: 'avenger' },
  { brand: 'renault', model: 'clio-grandtour' },
  { brand: 'iveco', model: 'daily' },
  { brand: 'peugeot', model: '408' },
  { brand: 'mazda', model: '6' },
  { brand: 'volvo', model: 's60' },
  { brand: 'peugeot', model: '207' },
  { brand: 'peugeot', model: '508' },
  { brand: 'renault', model: 'koleos' },
  { brand: 'dacia', model: 'logan-mcv' },
  { brand: 'suzuki', model: 'grand-vitara' },
  { brand: 'chevrolet', model: 'corvette' },
  { brand: 'volvo', model: 'v40' },
  { brand: 'citroen', model: 'c4-grand-picasso' },
  { brand: 'nissan', model: 'navara' },
  { brand: 'porsche', model: '911' },
  { brand: 'hyundai', model: 'i10' },
  { brand: 'toyota', model: 'yaris-cross' },
  { brand: 'renault', model: 'espace' },
  { brand: 'jaguar', model: 'xf' },
  { brand: 'dongfeng', model: 'u-tour' },
  { brand: 'toyota', model: 'camry' },
  { brand: 'citroen', model: 'c3-picasso' },
  { brand: 'honda', model: 'hr-v' },
  { brand: 'kia', model: 'ev6' },
  { brand: 'mazda', model: 'cx-3' },
  { brand: 'dacia', model: 'lodgy' },
  { brand: 'suzuki', model: 'jimny' },
  { brand: 'lexus', model: 'nx' },
  { brand: 'renault', model: 'kadjar' },
  { brand: 'mitsubishi', model: 'l-200' },
  { brand: 'jaecoo', model: '7' },
  { brand: 'peugeot', model: 'expert' },
  { brand: 'fiat', model: 'doblo' },
  { brand: 'mini', model: 'cooper-s' },
  { brand: 'kia', model: 'niro' },
  { brand: 'toyota', model: 'proace-city-verso' },
  { brand: 'seat', model: 'altea' },
  { brand: 'ssangyong', model: 'rexton' },
  { brand: 'cadillac', model: 'escalade' },
  { brand: 'toyota', model: 'aygo' },
  { brand: 'dacia', model: 'dokker' },
  { brand: 'fiat', model: 'tipo' },
  { brand: 'jeep', model: 'cherokee' },
  { brand: 'subaru', model: 'crosstrek' },
  { brand: 'hyundai', model: 'i40-cw' },
  { brand: 'opel', model: 'combo' },
  { brand: 'renault', model: 'thalia' },
  { brand: 'citroen', model: 'c4-cactus' },
  { brand: 'mazda', model: '2' },
  { brand: 'subaru', model: 'xv' },
  { brand: 'hyundai', model: 'ix20' },
  { brand: 'peugeot', model: '301' },
  { brand: 'jeep', model: 'renegade' },
  { brand: 'dongfeng', model: 't5-evo' },
  { brand: 'citroen', model: 'c5' },
  { brand: 'porsche', model: 'taycan' },
  { brand: 'jaguar', model: 'e-pace' },
  { brand: 'volvo', model: 's90' },
  { brand: 'opel', model: 'vivaro' },
  { brand: 'opel', model: 'zafira-tourer' },
  { brand: 'dacia', model: 'logan' },
  { brand: 'nissan', model: 'leaf' },
  { brand: 'dodge', model: 'challenger' },
  { brand: 'leapmotor', model: 'b10' },
  { brand: 'kia', model: 'picanto' },
  { brand: 'volvo', model: 'v50' },
  { brand: 'citroen', model: 'jumpy' },
  { brand: 'citroen', model: 'c-elysee' },
  { brand: 'fiat', model: 'freemont' },
  { brand: 'lexus', model: 'ux' },
  { brand: 'kgm', model: 'korando' },
  { brand: 'mazda', model: '5' },
  { brand: 'tesla', model: 'model-s' },
  { brand: 'omoda', model: '5-ice' },
  { brand: 'hyundai', model: 'ioniq-5' },
  { brand: 'volvo', model: 'ex90' },
  { brand: 'seat', model: 'altea-xl' },
  { brand: 'nissan', model: 'micra' },
  { brand: 'hyundai', model: 'staria' },
  { brand: 'kia', model: 'carens' },
  { brand: 'fiat', model: '600' },
  { brand: 'mini', model: 'one' },
  { brand: 'alfa-romeo', model: 'tonale' },
  { brand: 'chevrolet', model: 'camaro' },
  { brand: 'citroen', model: 'spacetourer' },
  { brand: 'dacia', model: 'spring' },
  { brand: 'mazda', model: 'cx-80' },
  { brand: 'mitsubishi', model: 'eclipse-cross' },
  { brand: 'ssangyong', model: 'torres' },
  { brand: 'byd', model: 'seal-u' },
  { brand: 'fiat', model: 'punto' },
  { brand: 'cupra', model: 'leon-sportstourer' },
  { brand: 'dodge', model: 'durango' },
  { brand: 'mitsubishi', model: 'pajero' },
  { brand: 'suzuki', model: 'ignis' },
  { brand: 'cupra', model: 'born' },
  { brand: 'tesla', model: 'model-x' },
  { brand: 'alfa-romeo', model: 'junior' },
  { brand: 'kia', model: 'venga' },
  { brand: 'fiat', model: '500x' },
  { brand: 'mitsubishi', model: 'lancer' },
  { brand: 'chevrolet', model: 'captiva' },
  { brand: 'mazda', model: 'cx-7' },
  { brand: 'suzuki', model: 's-cross' },
  { brand: 'cupra', model: 'ateca' },
  { brand: 'cupra', model: 'cupra-leon' },
  { brand: 'honda', model: 'jazz' },
  { brand: 'leapmotor', model: 'c10' },
  { brand: 'ds', model: '7-crossback' },
  { brand: 'alfa-romeo', model: 'giulia' },
  { brand: 'dongfeng', model: 'mage' },
  { brand: 'maserati', model: 'ghibli' },
  { brand: 'chery', model: 'tiggo-7' },
  { brand: 'nissan', model: 'pathfinder' },
  { brand: 'fiat', model: '500l' },
  { brand: 'jaguar', model: 'f-type' },
  { brand: 'dodge', model: 'charger' },
  { brand: 'byd', model: 'sealion-7' },
  { brand: 'byd', model: 'atto-2' },
  { brand: 'omoda', model: '9-shs' },
  { brand: 'volvo', model: 'v90-cc' },
  { brand: 'volvo', model: 'ex40' },
  { brand: 'citroen', model: 'c5-x' },
  { brand: 'seat', model: 'toledo' },
  { brand: 'mitsubishi', model: 'colt' },
  { brand: 'jaguar', model: 'xe' },
  { brand: 'jaguar', model: 'i-pace' },
  { brand: 'ssangyong', model: 'tivoli' },
  { brand: 'chevrolet', model: 'aveo' },
  { brand: 'baic', model: 'x7' },
  { brand: 'volvo', model: 'c40' },
  { brand: 'seat', model: 'leon-sp' },
  { brand: 'mitsubishi', model: 'grandis' },
  { brand: 'cupra', model: 'tavascan' },
  { brand: 'hongqi', model: 'hs3' },
  { brand: 'land-rover', model: 'freelander' },
  { brand: 'mazda', model: 'mx-5' },
  { brand: 'fiat', model: 'sedici' },
  { brand: 'porsche', model: 'carrera' },
  { brand: 'chevrolet', model: 'tahoe' },
  { brand: 'xpeng', model: 'g9' },
  { brand: 'volvo', model: 'v60-cc' },
  { brand: 'fiat', model: 'bravo' },
  { brand: 'fiat', model: 'talento' },
  { brand: 'porsche', model: 'cayman' },
  { brand: 'mini', model: 'clubman' },
  { brand: 'alfa-romeo', model: 'mito' },
  { brand: 'smart', model: 'fortwo-coupe' },
  { brand: 'lamborghini', model: 'urus' },
  { brand: 'forthing', model: 't5-evo' },
  { brand: 'mazda', model: 'mx-30' },
  { brand: 'nissan', model: 'note' },
  { brand: 'fiat', model: 'grande-punto' },
  { brand: 'fiat', model: '500e' },
  { brand: 'mitsubishi', model: 'space-star' },
  { brand: 'dongfeng', model: 'box-e3' },
  { brand: 'byd', model: 'dolphin-surf' },
  { brand: 'ds', model: '4' },
  { brand: 'ineos', model: 'grenadier' },
  { brand: 'porsche', model: 'boxster' },
  { brand: 'jaguar', model: 'xj' },
  { brand: 'jaguar', model: 'xk' },
  { brand: 'lexus', model: 'es' },
  { brand: 'alfa-romeo', model: 'giulietta' },
  { brand: 'chevrolet', model: 'cruze' },
  { brand: 'chevrolet', model: 'suburban' },
  { brand: 'chrysler', model: 'pacifica' },
  { brand: 'isuzu', model: 'd-max' },
  { brand: 'mg', model: 'ehs' },
  { brand: 'subaru', model: 'solterra' },
  { brand: 'mini', model: 'aceman' },
  { brand: 'leapmotor', model: 't03' },
  { brand: 'lada', model: 'niva' },
  { brand: 'gmc', model: 'yukon' },
  { brand: 'land-rover', model: 'freelander-2' },
  { brand: 'subaru', model: 'impreza' },
  { brand: 'jaguar', model: 's-type' },
  { brand: 'jaecoo', model: '5' },
  { brand: 'jaecoo', model: '7-shs' },
  { brand: 'ds', model: '4-crossback' },
  { brand: 'man', model: 'tge' },
  { brand: 'nissan', model: 'patrol' },
  { brand: 'mg', model: 'mg4' },
  { brand: 'mini', model: 'john-cooper-works' },
  { brand: 'chevrolet', model: 'orlando' },
  { brand: 'baic', model: 'x55' },
  { brand: 'hongqi', model: 'h5' },
  { brand: 'hongqi', model: 'hs5' },
  { brand: 'voyah', model: 'free' },
  { brand: 'mazda', model: '6e' },
  { brand: 'nissan', model: 'terrano' },
  { brand: 'jeep', model: 'gladiator' },
  { brand: 'honda', model: 'accord' },
  { brand: 'maserati', model: 'levante' },
  { brand: 'xpeng', model: 'g6' },
  { brand: 'hummer', model: 'h2' },
  { brand: 'seat', model: 'exeo' },
  { brand: 'porsche', model: '911-carrera-cabrio' },
  { brand: 'porsche', model: '911-turbo-gt3' },
  { brand: 'subaru', model: 'legacy' },
  { brand: 'subaru', model: 'legacy-kombi-wagon' },
  { brand: 'honda', model: 'zr-v' },
  { brand: 'ssangyong', model: 'actyon' },
  { brand: 'dongfeng', model: 'shine' },
  { brand: 'dongfeng', model: 'df-6' },
  { brand: 'kgm', model: 'rexton' },
  { brand: 'maserati', model: 'quattroporte' },
  { brand: 'chery', model: 'tiggo-9' },
  { brand: 'lancia', model: 'voyager' },
  { brand: 'lancia', model: 'delta' },
  { brand: 'abarth', model: '500' },
  { brand: 'abarth', model: '595' },
  { brand: 'bentley', model: 'continental-gt' },
  { brand: 'zeekr', model: '7x' },
  { brand: 'seat', model: 'terra' },
  { brand: 'seat', model: 'mii' },
  { brand: 'seat', model: 'ibiza-st' },
  { brand: 'nissan', model: 'townstar' },
  { brand: 'suzuki', model: 'splash' },
  { brand: 'jeep', model: 'patriot' },
  { brand: 'jeep', model: 'wagoneer' },
  { brand: 'subaru', model: 'brz' },
  { brand: 'jaguar', model: 'x-type' },
  { brand: 'lexus', model: 'gs' },
  { brand: 'lexus', model: 'ls' },
  { brand: 'alfa-romeo', model: '159-sportwagon' },
  { brand: 'chevrolet', model: 'spark' },
  { brand: 'byd', model: 'seal' },
  { brand: 'byd', model: 'seal-6' },
  { brand: 'kgm', model: 'torres' },
  { brand: 'baic', model: 'x35' },
  { brand: 'smart', model: 'hashtag-5' },
  { brand: 'ferrari', model: 'roma' },
  { brand: 'lada', model: 'vesta' },
  { brand: 'lamborghini', model: 'huracan' },
  { brand: 'lancia', model: 'thema' },
  { brand: 'gmc', model: 'sierra' },
  { brand: 'infiniti', model: 'fx' },
  { brand: 'saab', model: '9-3' },
  { brand: 'ich-x', model: 'k3' },
  { brand: 'nissan', model: '370-z' },
  { brand: 'nissan', model: 'nv200' },
  { brand: 'nissan', model: 'pulsar' },
  { brand: 'suzuki', model: 'across' },
  { brand: 'mg', model: 'cyberster' },
  { brand: 'mg', model: 'mg-s5' },
  { brand: 'porsche', model: 'panamera-sport-turismo' },
  { brand: 'porsche', model: '718' },
  { brand: 'lexus', model: 'is' },
  { brand: 'lexus', model: 'ct' },
  { brand: 'lexus', model: 'lc' },
  { brand: 'ssangyong', model: 'musso' },
  { brand: 'alfa-romeo', model: '159' },
  { brand: 'chevrolet', model: 'silverado' },
  { brand: 'dongfeng', model: 'shine-gs' },
  { brand: 'byd', model: 'tang' },
  { brand: 'byd', model: 'seal-5' },
  { brand: 'hongqi', model: 'ehs7' },
  { brand: 'smart', model: 'forfour' },
  { brand: 'chery', model: 'tiggo-8' },
  { brand: 'ferrari', model: 'purosangue' },
  { brand: 'gmc', model: 'canyon' },
  { brand: 'aston-martin', model: 'dbx' },
  { brand: 'bentley', model: 'bentayga' },
  { brand: 'zeekr', model: 'x' },
  { brand: 'dr', model: '50' },
  { brand: 'nissan', model: 'murano' },
  { brand: 'suzuki', model: 'alto' },
  { brand: 'porsche', model: '911-targa' },
  { brand: 'mitsubishi', model: 'pajero-wagon' },
  { brand: 'subaru', model: 'wrx-sti' },
  { brand: 'honda', model: 'legend' },
  { brand: 'honda', model: 'civic-type-r' },
  { brand: 'honda', model: 'civic-tourer' },
  { brand: 'mini', model: 'cabrio' },
  { brand: 'mini', model: 'cooper-sd' },
  { brand: 'mini', model: 'cooper-e' },
  { brand: 'ssangyong', model: 'tivoli-grand' },
  { brand: 'alfa-romeo', model: '147' },
  { brand: 'dongfeng', model: 'fengon-5' },
  { brand: 'dongfeng', model: 'box-e1' },
  { brand: 'baic', model: 'senova-x35' },
  { brand: 'smart', model: 'hashtag-3' },
  { brand: 'chery', model: 'tiggo-4' },
  { brand: 'ferrari', model: 'sf90' },
  { brand: 'xpeng', model: 'p7' },
  { brand: 'infiniti', model: 'qx' },
  { brand: 'zeekr', model: '001' },
  { brand: 'evo', model: '7' },
  { brand: 'evo', model: 'cuatro' },
  { brand: 'voyah', model: 'passion' },
  { brand: 'rolls-royce', model: 'cullinan' },
  { brand: 'suzuki', model: 'baleno' },
  { brand: 'jeep', model: 'commander' },
  { brand: 'subaru', model: 'justy' },
  { brand: 'honda', model: 'cr-z' },
  { brand: 'lexus', model: 'is-f' },
  { brand: 'chevrolet', model: 'malibu' },
  { brand: 'dodge', model: 'nitro' },
  { brand: 'dongfeng', model: 'glory-580' },
  { brand: 'dongfeng', model: 'forthing-t5-evo' },
  { brand: 'dongfeng', model: 'mhero' },
  { brand: 'byd', model: 'atto-3' },
  { brand: 'byd', model: 'dolphine' },
  { brand: 'ds', model: '3-crossback' },
  { brand: 'kgm', model: 'actyon' },
  { brand: 'cadillac', model: 'cts' },
  { brand: 'baic', model: 'bj30' },
  { brand: 'maserati', model: 'granturismo' },
  { brand: 'ferrari', model: 'california-t' },
  { brand: 'ferrari', model: '296' },
  { brand: 'lada', model: '2103' },
  { brand: 'lada', model: '4x4' },
  { brand: 'lamborghini', model: 'gallardo' },
  { brand: 'lamborghini', model: 'aventador' },
  { brand: 'lancia', model: 'musa' },
  { brand: 'lancia', model: 'ypsilon' },
  { brand: 'chrysler', model: 'grand-voyager' },
  { brand: 'chrysler', model: 'voyager' },
  { brand: 'aston-martin', model: 'v8-vantage' },
  { brand: 'aston-martin', model: 'db12' },
  { brand: 'infiniti', model: 'qx70' },
  { brand: 'evo', model: 'cross-4' },
  { brand: 'hummer', model: 'h3' },
  { brand: 'dr', model: '60' },
  { brand: 'mclaren', model: 'Artura' },
  { brand: 'mclaren', model: '750S' },
  { brand: 'ich-x', model: 'k2' },
  { brand: 'genesis', model: 'gv70' },
  { brand: 'sportequipe', model: '6-gt' },
  { brand: 'dfsk', model: 'fengon-5' },
  { brand: 'suzuki', model: 'liana' },
  { brand: 'suzuki', model: 'samurai' },
  { brand: 'suzuki', model: 'kizashi' },
  { brand: 'mg', model: 'f' },
  { brand: 'porsche', model: '992' },
  { brand: 'mitsubishi', model: 'pajero-pinin' },
  { brand: 'subaru', model: 'impreza-kombi-wagon' },
  { brand: 'subaru', model: 'levorg' },
  { brand: 'honda', model: 'fr-v' },
  { brand: 'honda', model: 'prelude' },
  { brand: 'honda', model: 'odyssey' },
  { brand: 'honda', model: 'pilot' },
  { brand: 'honda', model: 'ridgeline' },
  { brand: 'mini', model: 'cooper-cabrio' },
  { brand: 'mini', model: 'cooper-d' },
  { brand: 'jaguar', model: 'xjs' },
  { brand: 'lexus', model: 'lx' },
  { brand: 'lexus', model: 'rc-f' },
  { brand: 'ssangyong', model: 'kyron' },
  { brand: 'chevrolet', model: 'kalos' },
  { brand: 'chevrolet', model: 'traverse' },
  { brand: 'chevrolet', model: 'trax' },
  { brand: 'dodge', model: 'caliber' },
  { brand: 'dodge', model: 'grand-caravan' },
  { brand: 'dongfeng', model: 'box-e2' },
  { brand: 'omoda', model: '5-ev' },
  { brand: 'omoda', model: '5-shs-h' },
  { brand: 'kgm', model: 'tivoli' },
  { brand: 'cadillac', model: 'eldorado' },
  { brand: 'cadillac', model: 'seville' },
  { brand: 'maserati', model: 'grancabrio' },
  { brand: 'ferrari', model: '612-scaglietti' },
  { brand: 'lada', model: '1-10' },
  { brand: 'lada', model: '2105' },
  { brand: 'lada', model: 'kalina' },
  { brand: 'chrysler', model: 'pt-cruiser' },
  { brand: 'abarth', model: '595c' },
  { brand: 'abarth', model: '695c' },
  { brand: 'abarth', model: '595-turismo' },
  { brand: 'aston-martin', model: 'vanquish' },
  { brand: 'aston-martin', model: 'rapide' },
  { brand: 'aston-martin', model: 'db' },
  { brand: 'bentley', model: 'continental' },
  { brand: 'bentley', model: 'continental-gt-speed' },
  { brand: 'infiniti', model: 'q50' },
  { brand: 'forthing', model: 'u-tour' },
  { brand: 'ineos', model: 'quartermaster' },
  { brand: 'saab', model: '9-3-cabriolet' },
  { brand: 'saab', model: '9-5' },
  { brand: 'evo', model: '5' },
  { brand: 'hummer', model: 'ev' },
  { brand: 'rolls-royce', model: 'phantom' },
  { brand: 'rolls-royce', model: 'ghost' },
  { brand: 'mclaren', model: 'mp4-12c' },
  { brand: 'polestar', model: '2' },
  { brand: 'genesis', model: 'g70' },
  { brand: 'daewoo', model: 'nubira' },
  { brand: 'lincoln', model: 'continental' },
  { brand: 'lincoln', model: 'aviator' },
  { brand: 'tatra', model: 't613' },
  { brand: 'mahindra', model: 'xuv' },
  { brand: 'uaz', model: 'buchanka' },
  { brand: 'xev', model: 'yoyo' },
  { brand: 'land-rover', model: 'range-rover-vogue' },
  { brand: 'dacia', model: '1300' },
  { brand: 'mazda', model: '121' },
  { brand: 'jeep', model: 'cj' },
  { brand: 'mg', model: 'tf' },
  { brand: 'mg', model: 'marvel-r' },
  { brand: 'porsche', model: '968' },
  { brand: 'mitsubishi', model: 'carisma' },
  { brand: 'mitsubishi', model: 'eclipse' },
  { brand: 'mitsubishi', model: 'galant' },
  { brand: 'mitsubishi', model: 'pajero-sport' },
  { brand: 'subaru', model: 'legacy-outback' },
  { brand: 'subaru', model: 'tribeca' },
  { brand: 'tesla', model: 'cybertruck' },
  { brand: 'jaguar', model: 'x-type-estate' },
  { brand: 'jaguar', model: 'xjr' },
  { brand: 'jaguar', model: 'xjs-convertible' },
  { brand: 'jaguar', model: 'xk8-convertible' },
  { brand: 'lexus', model: 'sc' },
  { brand: 'lexus', model: 'hs' },
  { brand: 'lexus', model: 'rc' },
  { brand: 'ssangyong', model: 'rodius' },
  { brand: 'alfa-romeo', model: '156' },
  { brand: 'alfa-romeo', model: '166' },
  { brand: 'alfa-romeo', model: '4c' },
  { brand: 'chevrolet', model: 'cruze-sw' },
  { brand: 'dodge', model: 'journey' },
  { brand: 'dodge', model: 'stealth' },
  { brand: 'dongfeng', model: 'seres-3' },
  { brand: 'dongfeng', model: 'shine-e1' },
  { brand: 'byd', model: 'leopard-5' },
  { brand: 'iveco', model: 'massif' },
  { brand: 'ds', model: '3' },
  { brand: 'ds', model: '5' },
  { brand: 'ds', model: '9' },
  { brand: 'ds', model: 'n-4' },
  { brand: 'ds', model: 'n-8' },
  { brand: 'kgm', model: 'torres-evx' },
  { brand: 'kgm', model: 'musso-grand' },
  { brand: 'cadillac', model: 'srx' },
  { brand: 'cadillac', model: 'ats' },
  { brand: 'maserati', model: '3200-gt' },
  { brand: 'maserati', model: 'grecale' },
  { brand: 'hongqi', model: 'ehs9' },
  { brand: 'smart', model: 'roadster' },
  { brand: 'smart', model: 'fortwo-cabrio' },
  { brand: 'smart', model: 'pure' },
  { brand: 'smart', model: 'fortwo' },
  { brand: 'smart', model: 'eq-forfour' },
  { brand: 'ferrari', model: '550' },
  { brand: 'ferrari', model: '599' },
  { brand: 'ferrari', model: 'california-f149' },
  { brand: 'ferrari', model: 'f-430' },
  { brand: 'ferrari', model: 'mondial' },
  { brand: 'ferrari', model: '458' },
  { brand: 'ferrari', model: '488' },
  { brand: 'ferrari', model: 'f12-berlinetta' },
  { brand: 'ferrari', model: 'ff' },
  { brand: 'lada', model: '2106' },
  { brand: 'lamborghini', model: 'diablo' },
  { brand: 'lamborghini', model: 'gallardo-superleggera' },
  { brand: 'lamborghini', model: 'revuelto' },
  { brand: 'lancia', model: 'lybra' },
  { brand: 'lancia', model: 'phedra' },
  { brand: 'chrysler', model: '300-c' },
  { brand: 'chrysler', model: '300-c-touring' },
  { brand: 'chrysler', model: 'vision' },
  { brand: 'chrysler', model: 'le-baron' },
  { brand: 'abarth', model: 'punto-evo' },
  { brand: 'abarth', model: '695' },
  { brand: 'aston-martin', model: 'db7' },
  { brand: 'aston-martin', model: 'db9' },
  { brand: 'aston-martin', model: 'dbs' },
  { brand: 'bentley', model: 'arnage' },
  { brand: 'bentley', model: 'brooklands' },
  { brand: 'bentley', model: 'continental-flying-spur' },
  { brand: 'infiniti', model: 'ex' },
  { brand: 'infiniti', model: 'g' },
  { brand: 'infiniti', model: 'q30' },
  { brand: 'infiniti', model: 'q60' },
  { brand: 'zeekr', model: '7gt' },
  { brand: 'zeekr', model: '9x' },
  { brand: 'saab', model: '900' },
  { brand: 'saab', model: '9-5-sportcombi' },
  { brand: 'saab', model: '9-3-cabrio' },
  { brand: 'evo', model: '4' },
  { brand: 'voyah', model: 'dream' },
  { brand: 'dr', model: '10-ev' },
  { brand: 'dr', model: '60-t-gdi' },
  { brand: 'dr', model: 'pk8' },
  { brand: 'mclaren', model: '570gt' },
  { brand: 'mclaren', model: '540c' },
  { brand: 'genesis', model: 'gv80' },
  { brand: 'sportequipe', model: '7' },
  { brand: 'sportequipe', model: '8' },
  { brand: 'sportequipe', model: '7-gtw' },
  { brand: 'daewoo', model: 'espero' },
  { brand: 'lincoln', model: 'town-car' },
  { brand: 'buick', model: 'skylark' },
  { brand: 'alpina', model: 'b3' },
  { brand: 'alpina', model: 'xd3' },
  { brand: 'rover', model: '75' },
  { brand: 'rover', model: 'mini' },
  { brand: 'rover', model: '25' },
  { brand: 'tatra', model: '603' },
  { brand: 'aito', model: 'm5' },
  { brand: 'aito', model: 'm8' },
  { brand: 'aito', model: 'm7' },
  { brand: 'austin', model: 'allegro' },
  { brand: 'daihatsu', model: 'sirion' },
  { brand: 'daihatsu', model: 'terios' },
  { brand: 'lotus', model: 'emira' },
  { brand: 'maybach', model: 'gls' },
  { brand: 'pontiac', model: 'fiero' },
  { brand: 'trabant', model: '601' },
  { brand: 'great-wall', model: 'steed' },
  { brand: 'velor', model: 'x-trike' },
  { brand: 'corvette', model: 'c7' },
  { brand: 'ora', model: 'funky-cat' },
  { brand: 'foton', model: 'tunland-v9' },
  { brand: 'denza', model: 'n9' },
  { brand: 'geely', model: 'monjaro' },
];

export const autobazarEu: ScraperSource = {
  id: 'autobazar.eu',
  baseUrl: BASE,
  pageUrl({ page }) {
    const idx = (Math.max(1, page) - 1) % BRAND_MODEL_BUCKETS.length;
    const bucket = BRAND_MODEL_BUCKETS[idx]!;
    return bucket.model
      ? `${BASE}/vysledky/osobne-vozidla/${bucket.brand}/${bucket.model}/`
      : `${BASE}/vysledky/osobne-vozidla/${bucket.brand}/`;
  },
  parseListingsPage,
  detailUrl,
  parseDetailPage,
};
